
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Swift-ObjectMapper' do
    pod 'ObjectMapper', '~> 2.2'
    pod 'Alamofire', '~> 4.4'
    pod 'SVProgressHUD'
end
